// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/submissionService.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/susilo001/golang-advance/risk-profile-assement/entity"
)

// MockISubmissionService is a mock of ISubmissionService interface.
type MockISubmissionService struct {
	ctrl     *gomock.Controller
	recorder *MockISubmissionServiceMockRecorder
}

// MockISubmissionServiceMockRecorder is the mock recorder for MockISubmissionService.
type MockISubmissionServiceMockRecorder struct {
	mock *MockISubmissionService
}

// NewMockISubmissionService creates a new mock instance.
func NewMockISubmissionService(ctrl *gomock.Controller) *MockISubmissionService {
	mock := &MockISubmissionService{ctrl: ctrl}
	mock.recorder = &MockISubmissionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISubmissionService) EXPECT() *MockISubmissionServiceMockRecorder {
	return m.recorder
}

// CreateSubmission mocks base method.
func (m *MockISubmissionService) CreateSubmission(ctx context.Context, submission *entity.Submission) (entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubmission", ctx, submission)
	ret0, _ := ret[0].(entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubmission indicates an expected call of CreateSubmission.
func (mr *MockISubmissionServiceMockRecorder) CreateSubmission(ctx, submission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubmission", reflect.TypeOf((*MockISubmissionService)(nil).CreateSubmission), ctx, submission)
}

// DeleteSubmission mocks base method.
func (m *MockISubmissionService) DeleteSubmission(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubmission", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubmission indicates an expected call of DeleteSubmission.
func (mr *MockISubmissionServiceMockRecorder) DeleteSubmission(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubmission", reflect.TypeOf((*MockISubmissionService)(nil).DeleteSubmission), ctx, id)
}

// GetAllSubmissions mocks base method.
func (m *MockISubmissionService) GetAllSubmissions(ctx context.Context) ([]entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubmissions", ctx)
	ret0, _ := ret[0].([]entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSubmissions indicates an expected call of GetAllSubmissions.
func (mr *MockISubmissionServiceMockRecorder) GetAllSubmissions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubmissions", reflect.TypeOf((*MockISubmissionService)(nil).GetAllSubmissions), ctx)
}

// GetSubmissionByID mocks base method.
func (m *MockISubmissionService) GetSubmissionByID(ctx context.Context, id int) (entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmissionByID", ctx, id)
	ret0, _ := ret[0].(entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmissionByID indicates an expected call of GetSubmissionByID.
func (mr *MockISubmissionServiceMockRecorder) GetSubmissionByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmissionByID", reflect.TypeOf((*MockISubmissionService)(nil).GetSubmissionByID), ctx, id)
}

// UpdateSubmission mocks base method.
func (m *MockISubmissionService) UpdateSubmission(ctx context.Context, id int, submission *entity.Submission) (entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubmission", ctx, id, submission)
	ret0, _ := ret[0].(entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubmission indicates an expected call of UpdateSubmission.
func (mr *MockISubmissionServiceMockRecorder) UpdateSubmission(ctx, id, submission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubmission", reflect.TypeOf((*MockISubmissionService)(nil).UpdateSubmission), ctx, id, submission)
}

// MockISubmissionRepository is a mock of ISubmissionRepository interface.
type MockISubmissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISubmissionRepositoryMockRecorder
}

// MockISubmissionRepositoryMockRecorder is the mock recorder for MockISubmissionRepository.
type MockISubmissionRepositoryMockRecorder struct {
	mock *MockISubmissionRepository
}

// NewMockISubmissionRepository creates a new mock instance.
func NewMockISubmissionRepository(ctrl *gomock.Controller) *MockISubmissionRepository {
	mock := &MockISubmissionRepository{ctrl: ctrl}
	mock.recorder = &MockISubmissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISubmissionRepository) EXPECT() *MockISubmissionRepositoryMockRecorder {
	return m.recorder
}

// CreateSubmission mocks base method.
func (m *MockISubmissionRepository) CreateSubmission(ctx context.Context, submission *entity.Submission) (entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubmission", ctx, submission)
	ret0, _ := ret[0].(entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubmission indicates an expected call of CreateSubmission.
func (mr *MockISubmissionRepositoryMockRecorder) CreateSubmission(ctx, submission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubmission", reflect.TypeOf((*MockISubmissionRepository)(nil).CreateSubmission), ctx, submission)
}

// DeleteSubmission mocks base method.
func (m *MockISubmissionRepository) DeleteSubmission(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubmission", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubmission indicates an expected call of DeleteSubmission.
func (mr *MockISubmissionRepositoryMockRecorder) DeleteSubmission(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubmission", reflect.TypeOf((*MockISubmissionRepository)(nil).DeleteSubmission), ctx, id)
}

// GetAllSubmissions mocks base method.
func (m *MockISubmissionRepository) GetAllSubmissions(ctx context.Context) ([]entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubmissions", ctx)
	ret0, _ := ret[0].([]entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSubmissions indicates an expected call of GetAllSubmissions.
func (mr *MockISubmissionRepositoryMockRecorder) GetAllSubmissions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubmissions", reflect.TypeOf((*MockISubmissionRepository)(nil).GetAllSubmissions), ctx)
}

// GetSubmissionByID mocks base method.
func (m *MockISubmissionRepository) GetSubmissionByID(ctx context.Context, id int) (entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmissionByID", ctx, id)
	ret0, _ := ret[0].(entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmissionByID indicates an expected call of GetSubmissionByID.
func (mr *MockISubmissionRepositoryMockRecorder) GetSubmissionByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmissionByID", reflect.TypeOf((*MockISubmissionRepository)(nil).GetSubmissionByID), ctx, id)
}

// UpdateSubmission mocks base method.
func (m *MockISubmissionRepository) UpdateSubmission(ctx context.Context, id int, submission *entity.Submission) (entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubmission", ctx, id, submission)
	ret0, _ := ret[0].(entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubmission indicates an expected call of UpdateSubmission.
func (mr *MockISubmissionRepositoryMockRecorder) UpdateSubmission(ctx, id, submission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubmission", reflect.TypeOf((*MockISubmissionRepository)(nil).UpdateSubmission), ctx, id, submission)
}
